### ISSUE TITLE
Move the idyntree bindings outside from `floating_base_estimators` submodule

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/bipedal-locomotion-framework#442]
At the current stage if you want to load a KinDynConputations object in `blf` you should use the `floating_base_estimators` submodule

```python
import bipedal_locomotion_framework as blf                              
kindyn = blf.floating_base_estimators.KinDynComputations()
```

However, the `FloatingBaseEstimator` library is compiled only if 

https://github.com/ami-iit/bipedal-locomotion-framework/blob/d793ac71d80ace4fc3b793db94707f7d6f8113ea/cmake/BipedalLocomotionFrameworkDependencies.cmake#L150-L152

Furthermore, the `KinDyn` object can be used also outside the submodule.

I would suggest moving it to a new submodule called `idyntree`, the submodule will contain all the future bindings related to iDynTree

In this case, it will be possible to instantiate a kindyn object with 

```python
import bipedal_locomotion_framework as blf                              
kindyn = blf.idyntree.KinDynComputations()
```

what do you think? @ami-iit/blf-developers

**Comment by traversaro** [comment]
Good idea!

**Comment by prashanthr05** [comment]
Related issue: https://github.com/ami-iit/bipedal-locomotion-framework/issues/293

**Comment by GiulioRomualdi** [comment]
Ops! Sorry! I close this one in favour of #293
