### ISSUE TITLE
YarpSensorBridge not reading analog FT sensors

### ISSUE THREAD

**Issue by prashanthr05** [ami-iit/bipedal-locomotion-framework#455]
With @isorrentino we discovered a bug in YarpSensorBridge while trying to read six axis ft sensors connected as analog sensor clients to the YarpSensorBridge.
We are reading and populating only the MAS FT sensor buffers in,
https://github.com/ami-iit/bipedal-locomotion-framework/blob/b484cd0019abb46545c5655c7d1ba0773f8af53a/src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h#L1865-L1870

@isorrentino fixed this by adding a new method to properly read the analog FT sensors.

**Comment by isorrentino** [comment]
The related PR is coming. I needed to cleanup the code.
