### ISSUE TITLE
QPInverseKinematics and joint limit constraints?  

### ISSUE THREAD

**Issue by shikui08** [ami-iit/bipedal-locomotion-framework#530]
Has been using QPInverseKinematics for a while. Usage is similar to IK/tests/QPInverseKinematicsTest.cpp. 

Say I define a CoM task with highpriority and JointTracking task with lowpriority. It happens a lot that CoM is reached but the resulting joint positions violate urdf joint limits.

Is it possible for the solver to take into account joint limit constraint as well? 

Thanks.

**Comment by GiulioRomualdi** [comment]
Hi @shikui08 thank you for using bipedal locomotion framework! Yes it's something we should add in our formulation. I can allocate a timeslot to implement the feature. Otherwise if you need it in very a short time, you may try to implement the new task and open a PR

**Comment by shikui08** [comment]
> Hi @shikui08 thank you for using bipedal locomotion framework! Yes it's something we should add in our formulation. I can allocate a timeslot to implement the feature. Otherwise if you need it in very a short time, you may try to implement the new task and open a PR

Thanks for your reply. 
Considering whole body ik which respects pos limits I come across two codebases:
1) bio_ik. 
 
2) [https://github.com/mrsp/whole_body_ik/](url) 
It's Jacobian based, more straight forward, though it doesn't take into account task priorities.  

It turns out for me that each IK approach has it's pros and cons. And sometimes I find out that the result is more sensitive to the way the problem is defined, rather than the way the problem is solved.
Hope it helps~

**Comment by lrapetti** [comment]
Hi @shikui08, if you are interested you can also have a look at the QPinverseKinematics joint limits implementation used for https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9035059 and https://www.mdpi.com/1999-4893/13/10/266.

The implemented strategy is described in https://github.com/robotology/human-dynamics-estimation/issues/132, while the code can be found in https://github.com/robotology/human-dynamics-estimation/tree/master/HumanDynamicsEstimationLibrary.

**Comment by shikui08** [comment]
> Hi @shikui08, if you are interested you can also have a look at the QPinverseKinematics joint limits implementation used for https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9035059 and https://www.mdpi.com/1999-4893/13/10/266.
> 
> The implemented strategy is described in [robotology/human-dynamics-estimation#132](https://github.com/robotology/human-dynamics-estimation/issues/132), while the code can be found in https://github.com/robotology/human-dynamics-estimation/tree/master/HumanDynamicsEstimationLibrary.

Hi @lrapetti, thanks for your kind reply and great work. Glad to look further into the paper&code.

**Comment by GiulioRomualdi** [comment]
https://github.com/ami-iit/bipedal-locomotion-framework/pull/603 implements the joint limit constraints
