### ISSUE TITLE
YarpRobotLoggerDevice building error related to `opencv`

### ISSUE THREAD

**Issue by HosameldinMohamed** [ami-iit/bipedal-locomotion-framework#553]
Installing with enabling the `YarpRobotLoggerDevice` gives the following error:

```
In file included from /home/hosameldin/code/robotology-superbuild/src/bipedal-locomotion-framework/devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp:24:
/home/hosameldin/code/robotology-superbuild/src/bipedal-locomotion-framework/devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h:17:10: fatal error: opencv2/opencv.hpp: No such file or directory
   17 | #include <opencv2/opencv.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [devices/YarpRobotLoggerDevice/CMakeFiles/YarpRobotLoggerDevice.dir/build.make:76: devices/YarpRobotLoggerDevice/CMakeFiles/YarpRobotLoggerDevice.dir/src/YarpRobotLoggerDevice.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1727: devices/YarpRobotLoggerDevice/CMakeFiles/YarpRobotLoggerDevice.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I was on the release [`0.7.0`](https://github.com/ami-iit/bipedal-locomotion-framework/releases/tag/v0.7.0) then switched to @prashanthr05 's branch which is based on current `master`.

According to @prashanthr05, `opencv` is linked properly only if we set `FRAMEWORK_USE_PCL` to true. Actually when setting the option to true (and installing the dependency), the installation goes without error!

**Comment by GiulioRomualdi** [comment]
The CMake machinery should prevent you from building the logger without opencv. Thanks for reporting
