### ISSUE TITLE
Fix Documentation for TSID 

### ISSUE THREAD

**Issue by CarlottaSartore** [ami-iit/bipedal-locomotion-framework#632]
In the documentation there is written that the name to be set for the parameters of QPTSID is `robot_torque_variable_name`  but actually it is `joint_torque_variable_name`

**Comment by S-Dafarra** [comment]
Thanks for spotting it @CarlottaSartore! Feel free to open a PR

cc @GiulioRomualdi

**Comment by CarlottaSartore** [comment]
Opened PR #634

**Comment by GiulioRomualdi** [comment]
Fixed by https://github.com/ami-iit/bipedal-locomotion-framework/pull/634 
Thank you @CarlottaSartore
