### ISSUE TITLE
Bug in TSID  JointTrackingTask setSetPoint

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/bipedal-locomotion-framework#718]
https://github.com/ami-iit/bipedal-locomotion-framework/blob/e5c55ce16a9ae1880b0c3168a857a9de6fc1b2d4/src/TSID/src/JointTrackingTask.cpp#L182C5-L182C31

This should be acceleration

Spotted by @traversaro

**Comment by traversaro** [comment]
We found this with @Gio-DS
