### ISSUE TITLE
Make the project compiling with python 3.12

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/bipedal-locomotion-framework#751]
The CI is failing with following error
```
ModuleNotFoundError: No module named 'distutils'
```

This has been already seen in https://github.com/ami-iit/bipedal-locomotion-framework/pull/746#issuecomment-1784222364

**Comment by traversaro** [comment]
See https://github.com/robotology/robotology-superbuild/pull/1511 .
