### ISSUE TITLE
Conda force CI failure macOS December 2023

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/bipedal-locomotion-framework#780]
The macOs conda ci fails in solving the conda environment
https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/7210678527/job/19644360184?pr=779#step:4:838

@traversaro do you have any idea on why this is happening?

**Comment by traversaro** [comment]
I tried to reproduce this locally on Linux with:
~~~
CONDA_SUBDIR=osx-64 mamba create -n blfdev -c conda-forge -c robostack-staging "idyntree>=8.0.0" "yarp>=3.5.0" libmatio libmatio-cpp librobometry liblie-group-controllers eigen qhull "casadi>=3.5.5" cppad spdlog nlohmann_json manif manifpy pybind11 numpy pytest scipy opencv pcl tomlplusplus libunicycle-footstep-planner "icub-models>=1.23.4" ros-humble-rclcpp onnxruntime-cpp libbayes-filters-lib cmake make ninja pkg-config compilers
~~~

However, that works fine. Let's try to simplify the job of the solver by installing all the packages at once.
